### ISSUE TITLE
Fatal error: Declaration of DOMElement::getAttribute(string $qualifiedName) must be compatible with Serps\Core\Dom\DomNodeInterface::getAttribute($name)

### ISSUE THREAD

**Issue by jumaris88** [serp-scrape/serps#42]
I got error
Fatal error: Declaration of DOMElement::getAttribute(string $qualifiedName) must be compatible with Serps\Core\Dom\DomNodeInterface::getAttribute($name) in .../.../vendor/serps/core/src/Core/Dom/DomElement.php on line 0

**Comment by subet** [comment]
I have the same error message. Is there any solution?

**Comment by poznet** [comment]
same here

**Comment by UnknownX74m** [comment]
The error disappears if you start the script with php 7.4. 

But then I have another problem - maybe someone can help:
PHP Fatal error:  Uncaught Serps\SearchEngine\Google\Exception\InvalidDOMException: Unable to check javascript status. Google DOM has possibly changed and an update may be required. in /www/htdocs/xxx/vendor/serps/search-engine-google/src/Page/GoogleSerp.php:129
Stack trace:
#0 /www/htdocs/xxx/vendor/serps/search-engine-google/src/Page/GoogleSerp.php(40): Serps\SearchEngine\Google\Page\GoogleSerp->javascriptIsEvaluated()
#1 /www/htdocs/xxx/_webseiten/avigio.de.crm/serp.php(24): Serps\SearchEngine\Google\Page\GoogleSerp->getNaturalResults()
#2 {main}
  thrown in /www/htdocs/xxx/vendor/serps/search-engine-google/src/Page/GoogleSerp.php on line 129
